export default {
  nuxtServerInit: 'nuxtServerInit',
  // ACTION
  GET_APP_CONFIG: 'GET_APP_CONFIG',
  AUTH_JWT_ACTION: 'AUTH_JWT_ACTION',
  CREATE_REQUEST: 'CREATE_REQUEST',
  // MUTATION
  SET_APP_CONFIG: 'SET_APP_CONFIG',
  SET_APP_CONFIG_LOADING: 'SET_APP_CONFIG_LOADING',
  SET_APP_GLOBAL_LOADING: 'SET_APP_GLOBAL_LOADING',
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
  SET_REFRESH_TOKEN: 'SET_REFRESH_TOKEN',
  SET_DECODE_JWT: 'SET_DECODE_JWT',
}

export const SHOW_SIDE_PANEL = 'SHOW_SIDE_PANEL'

export const SET_SIDE_PANEL_PAGE = 'SET_SIDE_PANEL_PAGE'
